_enabled_editors:
  - visual
  - content

data_config: true

_editables:
  content:
    blockquote: true
    bold: true
    bulletedlist: true
    center: align-center
    code: true
    copyformatting: true
    correct_orientation: true
    embed: true
    expandable: true
    format: 'p h1 h2 h3 h4 h5 h6 pre address div'
    height: 888
    horizontalrule: true
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    justify: align-justify
    left: align-left
    link: true
    mime_type: image/png
    numberedlist: true
    outdent: true
    paths:
      uploads: static/images
      dam_uploads:
      dam_static:
    redo: true
    removeformat: true
    resize_style: stretch
    right: align-right
    snippet: true
    strike: true
    styles:
    subscript:
    superscript:
    table:
    underline:
    undo:
    width:
collections_config:
  data:
    path: data
    icon: nature_people
    _inputs:
      # company
      name:
        label: Name label defined on the collections_config
  posts:
    _enabled_editors:
      - content
      - visual
_inputs:
  content_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_horizontal_left
          name: Left
        - icon: align_horizontal_center
          name: Center
        - icon: align_horizontal_right
          name: Right
  vertical_alignment:
    type: choice
    options:
      text_key: false
      value_key: name
      values:
        - icon: align_vertical_top
          name: Top
        - icon: align_vertical_center
          name: Middle
        - icon: align_vertical_bottom
          name: Bottom
  content_width:
    type: choice
    options:
      values:
        - name: Small
          icon: width_normal
        - name: Medium
          icon: width_wide
        - name: Large
          icon: rectangle